version: "3"
services:
  service.v2fly:
    image: v2fly/v2fly-core
    container_name: v2fly
    volumes:
      - ./config/config.json:/etc/v2ray/config.json
    network_mode: host
    restart: always
