version: "3"
services:
  service.v2fly:
    image: thatszer/v2ray
    container_name: v2ray
    volumes:
      - ./config.json:/config.json
    network_mode: host
    command: ["/bin/sh", "/v2ray.sh", "${ID}"]
    restart: always
